[project]
name = "csv-merger"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pandas==2.0.0",
    "streamlit==1.28.0",
]
